### ISSUE TITLE
PostgreSQL Database directory appears to contain a database; Skipping initialization

### ISSUE THREAD

**Issue by snarayan23** [mikeizbicki/cmc-csci143#336]
Hi Mike, 

I'm running into the same issue again where even after running the commands in step 0.4 of the instructions to reset the containers, it skips initialization for both normalized batch and denormalized. Is there another command I should be running or would you be able to delete the `$HOME/bigdata/pg_normalized_batch` and `$HOME/bigdata/pg_denormalized` folder again like you mentioned in previous issues (https://github.com/mikeizbicki/cmc-csci143/issues/332)? 

Thank You!

**Comment by hfmandell** [comment]
+1

**Comment by snarayan23** [comment]
I was able to resolve it for now and get the container running. I exited out of the terminal and re ran the commands and was able to get it to work.

**Comment by hfmandell** [comment]
^ resolved, it simply took a while for the database to accept connections, as mentioned by @BITEEE0308 in #337

**Comment by kushpetal** [comment]
+1 
having the same issue

**Comment by snarayan23** [comment]
After running` docker-compose up -d --build`, I still get the following log statements. The containers are running, however, it skips initialization for both pg_denormalized and pg_normalized_batch. Did anyone else see this in the logs after the build? 

```
Attaching to twitter_postgres_indexes_pg_denormalized_1, twitter_postgres_indexes_pg_normalized_batch_1
pg_denormalized_1      | 
pg_denormalized_1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
pg_denormalized_1      | 
pg_denormalized_1      | 2023-04-24 00:20:01.398 UTC [1] LOG:  starting PostgreSQL 13.10 (Debian 13.10-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
pg_denormalized_1      | 2023-04-24 00:20:01.398 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pg_denormalized_1      | 2023-04-24 00:20:01.398 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pg_denormalized_1      | 2023-04-24 00:20:01.399 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pg_denormalized_1      | 2023-04-24 00:20:01.402 UTC [27] LOG:  database system was shut down at 2023-04-24 00:19:31 UTC
pg_denormalized_1      | 2023-04-24 00:20:01.406 UTC [1] LOG:  database system is ready to accept connections
pg_normalized_batch_1  | 
pg_normalized_batch_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
pg_normalized_batch_1  | 
pg_normalized_batch_1  | 2023-04-24 00:20:02.253 UTC [1] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
pg_normalized_batch_1  | 2023-04-24 00:20:02.253 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pg_normalized_batch_1  | 2023-04-24 00:20:02.253 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pg_normalized_batch_1  | 2023-04-24 00:20:02.254 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pg_normalized_batch_1  | 2023-04-24 00:20:02.258 UTC [29] LOG:  database system was shut down at 2023-04-24 00:19:31 UTC
pg_normalized_batch_1  | 2023-04-24 00:20:02.264 UTC [1] LOG:  database system is ready to accept connections

```

**Comment by snarayan23** [comment]
^Resolved after a while
